sources:
  - name: nft
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/amxx/eip721-subgraph
        batch: false

    transforms:
      - rename:
          - from:
              type: Account
            to:
              type: User
      - typeMerging:
          queryFields:
            # With batching
            - queryFieldName: accounts
              keyField: id
              keyArg: 'where.id_in'

  - name: uniswap
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
        batch: false
    transforms:
      - typeMerging:
          queryFields:
            # Without batching
            - queryFieldName: user
              keyField: id
              keyArg: id

documents:
  - ./operations/**/*.graphql
  

serve:
  browser: false